version: '3.8'

networks:
  adbhoney_local:

services:

  adbhoney:
    container_name: adbhoney
    restart: always
    networks:
     - adbhoney_local
    ports:
     - "5555:5555"
    image: "${USERNAME}/${IMAGENAME}:${TAG}"
    volumes:
     - ${ARMEDPOTPATH}/adbhoney/log:/opt/adbhoney/log
     - ${ARMEDPOTPATH}/adbhoney/downloads:/opt/adbhoney/dl
     
